import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import { ReduxProvider } from '@/redux/provider'
import { Header } from '@/components/layout/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies()
  const theme = cookieStore.get('color-theme')
  const themeClass = theme ? theme.value : 'not'
  return (
    <html lang='en' className={themeClass}>
      <ReduxProvider>
        <body className={`${inter.className} bg-gray-700 dark:bg-black`}>
          <Header></Header>
          <main>{children}</main>
        </body>
      </ReduxProvider>
    </html>
  )
}
